name: bearlysocial
version: 2.0.0
description: A safe social space.

publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_snack_bar: ^0.4.0
  camera: 0.10.5+5
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  easy_localization: ^3.0.6
  flutter_image_compress: ^2.1.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.6
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_ml_kit: ^0.16.2
  hashlib: ^1.12.0
  http: ^1.1.0
  http_parser: ^4.0.2
  http_status_code: ^0.0.2
  image: ^4.1.2
  interval_time_picker: ^2.0.0+5
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  omni_datetime_picker: ^1.1.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pngs/
    - assets/svgs/
